#!/usr/bin/env bash
#
# 1-create-sensor-pipelines.sh — generate per-sensor Cowrie ingest pipeline files.
#
# Each sensor must stamp a distinct observer.name so the session-rollup `_id`
# (`<observer.name>:<session_id>`) is unique across sensors and upserts can't
# collide (P6.2 / scale-decision D3). Cowrie here doesn't emit a sensor field,
# so we stamp it at ingest with a thin per-sensor pipeline that sets
# observer.name then delegates to the shared base pipeline `prism.cowrie.session`
# (the base only renames cowrie.sensor -> observer.name when unset, so the
# stamped value wins).
#
# This prompts for 1+ sensor names (or takes them as args), writes
# setup/es-pipelines/cowrie-pipeline-sensor-<name>.yml for each NEW name, reports
# any names that already exist, and NEVER edits an existing sensor file.
#
# Usage:
#   setup/1-create-sensor-pipelines.sh                 # interactive prompt
#   setup/1-create-sensor-pipelines.sh honey-eu-1 honey-us-2
#
# After running:
#   1. Apply the new pipeline(s):
#        sudo -u dshield_prism .venv/bin/python -m enrich.cli bootstrap-es
#      (or PUT each file body in Kibana Dev Tools).
#   2. Set that sensor's Fleet Cowrie integration `pipeline:` field to
#      prism.cowrie.session.<name>.
#
# Alternative to a per-sensor pipeline: stamp observer.name with an `add_fields`
# processor in the per-sensor agent policy and keep one shared pipeline.

set -euo pipefail
shopt -s nullglob

readonly BASE="prism.cowrie.session"
readonly FILE_PREFIX="cowrie-pipeline-sensor-"
# id-safe: starts alnum, then letters/digits/_/- only. No spaces, ':' or '.' —
# the name becomes the pipeline-id suffix and the rollup `_id` namespace.
readonly NAME_RE='^[A-Za-z0-9][A-Za-z0-9_-]*$'

PIPE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/es-pipelines" && pwd)"
readonly PIPE_DIR
readonly BASE_RE="${BASE//./\\.}"

# --- existing sensors: read the pipeline id out of each generated file -------
existing=""   # newline-separated names
for f in "$PIPE_DIR/${FILE_PREFIX}"*.yml; do
  n="$(sed -n "s|^PUT _ingest/pipeline/${BASE_RE}\.\([A-Za-z0-9_-]\{1,\}\).*|\1|p" "$f" | head -n1)"
  [ -n "$n" ] && existing+="${n}"$'\n'
done

if [ -n "$existing" ]; then
  echo "Existing sensor pipelines (left untouched):"
  printf '%s' "$existing" | sort -u | sed 's/^/  - /'
else
  echo "No existing sensor pipelines in ${PIPE_DIR#"$PWD"/}."
fi

# --- gather requested names (args, else prompt) ------------------------------
names=("$@")
if [ "${#names[@]}" -eq 0 ]; then
  echo
  read -rp "Sensor name(s) to create (space-separated): " -a names || true
fi
if [ "${#names[@]}" -eq 0 ]; then
  echo "No names given; nothing to do."
  exit 0
fi

# --- generate ----------------------------------------------------------------
created=0
skipped=0
processed=""       # newline-separated, to catch dupes within this request
created_names=""   # newline-separated, names created this run
echo
for name in "${names[@]}"; do
  if ! [[ "$name" =~ $NAME_RE ]]; then
    echo "  SKIP   '$name' — invalid (letters/digits/_/- only; no spaces, ':' or '.')"
    skipped=$((skipped + 1)); continue
  fi
  if printf '%s' "$processed" | grep -Fxq -- "$name"; then
    echo "  SKIP   '$name' — duplicate in this request"
    skipped=$((skipped + 1)); continue
  fi
  processed+="${name}"$'\n'

  out="$PIPE_DIR/${FILE_PREFIX}${name}.yml"
  # Two independent guards so an existing sensor is never edited: by name (from
  # any generated file's pipeline id) and by target path.
  if printf '%s' "$existing" | grep -Fxq -- "$name" || [ -e "$out" ]; then
    echo "  EXISTS '$name' — already defined; not touching it"
    skipped=$((skipped + 1)); continue
  fi

  cat > "$out" <<EOF
PUT _ingest/pipeline/${BASE}.${name}
{
  "description": "Per-sensor Cowrie wrapper for '${name}' (P6.2 / D3): stamp observer.name, then run the base pipeline ${BASE}. Generated by setup/1-create-sensor-pipelines.sh; re-running never overwrites it.",
  "processors": [
    { "set": { "field": "observer.name", "value": "${name}", "override": false } },
    { "pipeline": { "name": "${BASE}" } }
  ]
}
EOF
  created_names+="${name}"$'\n'
  echo "  CREATE '$name' -> ${BASE}.${name}  (es-pipelines/${FILE_PREFIX}${name}.yml)"
  created=$((created + 1))
done

echo
echo "Done: ${created} created, ${skipped} skipped."

# Pipeline id for every known sensor (existing + created this run). These are
# the exact values to paste into each sensor's Fleet integration 'pipeline:'
# field, so print the full mapping regardless of which run created which.
all_names="$(printf '%s%s' "$existing" "$created_names" | sed '/^$/d' | sort -u)"
if [ -n "$all_names" ]; then
  echo
  echo "Sensor  ->  ingest pipeline id (set each sensor's Fleet Cowrie"
  echo "integration 'pipeline:' field to its id, once the pipelines are applied):"
  while IFS= read -r n; do
    printf '  %-24s %s.%s\n' "$n" "$BASE" "$n"
  done <<< "$all_names"
  echo
  echo "Apply the pipelines with 2-setup.sh (rsync + bootstrap-es), or directly:"
  echo "  sudo -u dshield_prism .venv/bin/python -m enrich.cli bootstrap-es"
fi
