"""Findings v2 — lifecycle subsystem (step 1).

One doc per `playbook_id` / `campaign_id` / `source.ip`. Each doc carries:

  - `first_seen_ever`, `last_seen`, `first_run_id`, `last_run_id`,
    `runs_observed`, `silent_runs_current`
  - `snapshots[]` — rolling cap N per-run snapshots (default 30)
  - `confirm_anchors[]` — append-only history (analyst + provisional;
    written by step 2)
  - `drift_suppressions[]` — `delta_signature`s the analyst rejected
    (written by step 2)

Step 1 ships only the snapshot append + silent-run bump path; anchors
and suppressions stay empty until step 2 lands `mutate_status` side
effects.

`run_track_lifecycles` is the orchestrator wired into the CLI `track
lifecycles` verb. It queries the cluster + rollup + campaign + intel
indices to materialise this-run snapshots, upserts the lifecycle docs,
then bumps `silent_runs_current` on any artifact that was not touched
this run.
"""
from __future__ import annotations

import logging
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Iterable, Optional

from elasticsearch import Elasticsearch

log = logging.getLogger(__name__)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _read_doc(es: Elasticsearch, index: str, doc_id: str) -> dict:
    try:
        existing = es.get(index=index, id=doc_id)
        return existing.get("_source") or {}
    except Exception:
        return {}


def _apply_snapshot(
    doc: dict,
    *,
    snapshot: dict,
    run_id: str,
    snapshot_cap: int,
    key_field: str,
    key_value: Any,
    extra_init: Optional[dict] = None,
) -> dict:
    """In-place merge of a new snapshot into a lifecycle doc.

    `doc` may be empty (new artifact) — caller's `_read_doc` returns `{}`
    when the id doesn't exist yet. Pure function over the doc dict; the
    caller writes the result back to ES.
    """
    now = snapshot.get("@timestamp") or _now_iso()
    if not doc:
        doc = {
            key_field: key_value,
            "first_seen_ever": now,
            "first_run_id": run_id,
            "runs_observed": 0,
            "silent_runs_current": 0,
            "snapshots": [],
            "confirm_anchors": [],
            "drift_suppressions": [],
        }
        if extra_init:
            doc.update(extra_init)
    # Source-IP lifecycle has no confirm_anchors[] / drift_suppressions[] —
    # the strict mapping rejects those fields. Drop them on the source_ip path.
    doc["last_seen"] = now
    doc["last_run_id"] = run_id
    doc["runs_observed"] = int(doc.get("runs_observed", 0)) + 1
    doc["silent_runs_current"] = 0
    snaps = list(doc.get("snapshots") or [])
    snaps.append(snapshot)
    if len(snaps) > snapshot_cap:
        snaps = snaps[-snapshot_cap:]
    doc["snapshots"] = snaps
    return doc


def update_playbook_lifecycle(
    es: Elasticsearch,
    index: str,
    *,
    playbook_id: str,
    playbook_name: Optional[str],
    run_id: str,
    snapshot: dict,
    snapshot_cap: int = 30,
) -> str:
    """Upsert a single playbook lifecycle doc. Returns the doc id."""
    doc = _read_doc(es, index, playbook_id)
    extra: dict = {}
    if playbook_name:
        extra["playbook_name"] = playbook_name
    doc = _apply_snapshot(
        doc,
        snapshot=snapshot,
        run_id=run_id,
        snapshot_cap=snapshot_cap,
        key_field="playbook_id",
        key_value=playbook_id,
        extra_init=extra,
    )
    # Refresh the human-readable name on every run — it may have been
    # regenerated by `name playbooks`.
    if playbook_name:
        doc["playbook_name"] = playbook_name
    es.index(index=index, id=playbook_id, document=doc, refresh=False)
    return playbook_id


def update_campaign_lifecycle(
    es: Elasticsearch,
    index: str,
    *,
    campaign_id: str,
    campaign_name: Optional[str],
    campaign_kind: Optional[str],
    run_id: str,
    snapshot: dict,
    snapshot_cap: int = 30,
) -> str:
    """Upsert a single campaign lifecycle doc. Returns the doc id."""
    doc = _read_doc(es, index, campaign_id)
    extra: dict = {}
    if campaign_name:
        extra["campaign_name"] = campaign_name
    if campaign_kind:
        extra["campaign_kind"] = campaign_kind
    doc = _apply_snapshot(
        doc,
        snapshot=snapshot,
        run_id=run_id,
        snapshot_cap=snapshot_cap,
        key_field="campaign_id",
        key_value=campaign_id,
        extra_init=extra,
    )
    if campaign_name:
        doc["campaign_name"] = campaign_name
    if campaign_kind:
        doc["campaign_kind"] = campaign_kind
    es.index(index=index, id=campaign_id, document=doc, refresh=False)
    return campaign_id


def update_source_ip_lifecycle(
    es: Elasticsearch,
    index: str,
    *,
    source_ip: str,
    run_id: str,
    snapshot: dict,
    snapshot_cap: int = 30,
) -> str:
    """Upsert a single source-IP lifecycle doc. Returns the doc id.

    IP lifecycle has no `confirm_anchors[]` / `drift_suppressions[]` —
    `ip_behavior_shift` self-anchors against the IP's own snapshot
    history, so the analyst confirmation surface doesn't apply.
    """
    doc = _read_doc(es, index, source_ip)
    doc = _apply_snapshot(
        doc,
        snapshot=snapshot,
        run_id=run_id,
        snapshot_cap=snapshot_cap,
        key_field="source_ip",
        key_value=source_ip,
    )
    # Strict-dynamic source_ip mapping forbids these fields.
    doc.pop("confirm_anchors", None)
    doc.pop("drift_suppressions", None)
    es.index(index=index, id=source_ip, document=doc, refresh=False)
    return source_ip


def increment_silent_runs(
    es: Elasticsearch,
    index: str,
    *,
    current_run_id: str,
) -> int:
    """Bump `silent_runs_current` on every lifecycle doc whose
    `last_run_id` does not equal `current_run_id` — i.e. the ones we
    did NOT touch this run. Used as the silent-run accumulator for
    `playbook_resurgence` later (step 4).

    Returns the number of docs updated. `0` is fine on first run.
    """
    if not es.indices.exists(index=index):
        return 0
    body = {
        "query": {
            "bool": {
                "must_not": [
                    {"term": {"last_run_id": current_run_id}},
                ]
            }
        },
        "script": {
            "source": (
                "ctx._source.silent_runs_current = "
                "(ctx._source.silent_runs_current == null ? 0 : ctx._source.silent_runs_current) + 1;"
            ),
            "lang": "painless",
        },
    }
    try:
        resp = es.update_by_query(index=index, body=body, refresh=True, conflicts="proceed")
        return int(resp.get("updated") or 0)
    except Exception as exc:
        log.warning("[lifecycle] silent-run bump on %s failed: %s", index, exc)
        return 0


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def _iter_current_playbooks(
    es: Elasticsearch, session_clusters_idx: str, sessions_idx: str
) -> Iterable[dict]:
    """Yield per-playbook aggregates for the most recent cluster run.

    Output dict shape:
        {playbook_id, playbook_name, session_count, ip_count,
         mean_novelty, dominant_intent, asn_top, asn_distribution}
    """
    if not es.indices.exists(index=session_clusters_idx):
        return
    # 1) Find the latest cluster run id.
    resp = es.search(
        index=session_clusters_idx,
        size=1,
        query={"term": {"doc_type": "cluster"}},
        sort=[{"@timestamp": "desc"}],
        _source=["run_id"],
    )
    hits = resp["hits"]["hits"]
    if not hits:
        return
    latest_run = hits[0]["_source"].get("run_id")
    if not latest_run:
        return

    # 2) All playbook ids for that run. A playbook may span multiple
    # cluster docs (merged via session.playbook_merge_threshold); collapse
    # to one entry per playbook_id.
    resp2 = es.search(
        index=session_clusters_idx,
        size=1000,
        query={"bool": {"must": [
            {"term": {"doc_type": "cluster"}},
            {"term": {"run_id": latest_run}},
        ]}},
        _source=["playbook_id", "playbook_name"],
    )
    by_id: dict[str, dict] = {}
    for h in resp2["hits"]["hits"]:
        src = h["_source"]
        pid = src.get("playbook_id")
        if not pid:
            continue
        if pid not in by_id:
            by_id[pid] = {
                "playbook_id": pid,
                "playbook_name": src.get("playbook_name"),
            }

    # 3) For each playbook id, aggregate from sessions_rollup.
    cluster_field = "dshield.cowrie.enrichment.session.playbook_id"
    novelty_field = "dshield.cowrie.enrichment.session.cluster.novelty_score"
    intent_field  = "dshield.cowrie.enrichment.session.dominant_intent"
    asn_field     = "source.as.number"
    ip_field      = "source.ip"

    for pid, base in by_id.items():
        try:
            agg_resp = es.search(
                index=sessions_idx,
                size=0,
                query={"term": {cluster_field: pid}},
                aggs={
                    "session_count":  {"value_count": {"field": cluster_field}},
                    "ip_count":       {"cardinality": {"field": ip_field}},
                    "mean_novelty":   {"avg": {"field": novelty_field}},
                    "dominant_intent":{"terms": {"field": intent_field, "size": 1}},
                    "asn_top":        {"terms": {"field": asn_field,    "size": 10}},
                },
            )
        except Exception as exc:
            log.warning("[lifecycle] agg for playbook %s failed: %s", pid, exc)
            continue
        aggs = agg_resp.get("aggregations") or {}
        sc = int(((aggs.get("session_count") or {}).get("value")) or 0)
        ic = int(((aggs.get("ip_count") or {}).get("value")) or 0)
        mn = float(((aggs.get("mean_novelty") or {}).get("value")) or 0.0)
        di_buckets = ((aggs.get("dominant_intent") or {}).get("buckets")) or []
        di = di_buckets[0]["key"] if di_buckets else None
        asn_buckets = ((aggs.get("asn_top") or {}).get("buckets")) or []
        asn_top = str(asn_buckets[0]["key"]) if asn_buckets else None
        asn_distribution = {str(b["key"]): int(b["doc_count"]) for b in asn_buckets}
        yield {
            **base,
            "session_count": sc,
            "ip_count": ic,
            "mean_novelty": mn,
            "dominant_intent": di,
            "asn_top": asn_top,
            "asn_distribution": asn_distribution,
        }


def _iter_current_campaigns(es: Elasticsearch, campaigns_idx: str) -> Iterable[dict]:
    """Yield per-campaign aggregates from the latest snapshot of the campaigns index."""
    if not es.indices.exists(index=campaigns_idx):
        return
    body = {
        "size": 1000,
        "query": {"match_all": {}},
        "_source": [
            "campaign_id", "campaign_name", "kind",
            "session_count", "ip_count", "mean_novelty",
            "dominant_intent", "asn_distribution",
        ],
        "sort": [{"@timestamp": "desc"}, {"_doc": "asc"}],
    }
    try:
        resp = es.search(index=campaigns_idx, **body)
    except Exception as exc:
        log.warning("[lifecycle] campaigns scan failed: %s", exc)
        return
    seen: set[str] = set()
    for h in resp["hits"]["hits"]:
        src = h["_source"]
        cid = src.get("campaign_id")
        if not cid or cid in seen:
            continue
        seen.add(cid)
        asn_dist = src.get("asn_distribution") or {}
        asn_top = None
        if isinstance(asn_dist, dict) and asn_dist:
            asn_top = str(max(asn_dist.items(), key=lambda kv: kv[1])[0])
        yield {
            "campaign_id":      cid,
            "campaign_name":    src.get("campaign_name"),
            "campaign_kind":    src.get("kind"),
            "session_count":    int(src.get("session_count") or 0),
            "ip_count":         int(src.get("ip_count") or 0),
            "mean_novelty":     float(src.get("mean_novelty") or 0.0),
            "dominant_intent":  src.get("dominant_intent"),
            "asn_top":          asn_top,
            "asn_distribution": asn_dist if isinstance(asn_dist, dict) else {},
        }


def _iter_current_ips(es: Elasticsearch, ips_idx: str) -> Iterable[dict]:
    """Yield per-IP snapshot input from the IP rollup index."""
    if not es.indices.exists(index=ips_idx):
        return
    body = {
        "size": 1000,
        "_source": [
            "source.ip",
            "source.as.number",
            "source.geo.country_iso_code",
            "dshield.cowrie.enrichment.ip.total_sessions",
            "dshield.cowrie.enrichment.ip.dominant_playbook_id",
            "dshield.cowrie.enrichment.ip.playbook_distribution",
            "dshield.cowrie.enrichment.ip.intel.consensus_verdict",
            "dshield.cowrie.enrichment.ip.intel.consensus_score",
        ],
        "query": {"exists": {"field": "source.ip"}},
        "sort": [{"@timestamp": "asc"}, {"_doc": "asc"}],
    }
    search_after = None
    while True:
        if search_after:
            body["search_after"] = search_after
        try:
            resp = es.search(index=ips_idx, **body)
        except Exception as exc:
            log.warning("[lifecycle] ip scan failed: %s", exc)
            return
        hits = resp["hits"]["hits"]
        if not hits:
            return
        for h in hits:
            src = h["_source"]
            ip = ((src.get("source") or {}).get("ip"))
            if not ip:
                continue
            enr = ((src.get("dshield") or {}).get("cowrie", {}).get("enrichment", {}).get("ip", {})) or {}
            pd_raw = enr.get("playbook_distribution") or []
            pd_flat: dict[str, int] = {}
            if isinstance(pd_raw, list):
                for entry in pd_raw:
                    if isinstance(entry, dict) and entry.get("playbook_id"):
                        pd_flat[entry["playbook_id"]] = int(entry.get("count") or 0)
            intel = enr.get("intel") or {}
            yield {
                "source_ip":              ip,
                "session_count":          int(enr.get("total_sessions") or 0),
                "dominant_playbook_id":   enr.get("dominant_playbook_id"),
                "playbook_distribution":  pd_flat,
                "intel_verdict":          intel.get("consensus_verdict"),
                "intel_consensus_score":  float(intel.get("consensus_score") or 0.0),
                "asn":                    ((src.get("source") or {}).get("as") or {}).get("number"),
                "geo_country":            ((src.get("source") or {}).get("geo") or {}).get("country_iso_code"),
            }
        search_after = hits[-1]["sort"]


def run_track_lifecycles(cfg, secrets, *, dry_run: bool = False) -> dict:
    """End-to-end lifecycle pass: append this-run snapshots for every active
    playbook, campaign, and source IP; bump `silent_runs_current` on the rest.

    Step 1 scope: snapshots only. Anchors (analyst + provisional) and drift
    suppressions land in step 2. Drift detectors (step 4) consume the
    snapshots + anchors this writer produces.
    """
    from ..es_client import make_client
    es = make_client(cfg.elasticsearch, secrets)

    cap = int(cfg.findings.lifecycle.snapshot_cap)
    f_idx = cfg.findings.indexes
    cowrie_idx = cfg.elasticsearch.indexes.cowrie

    run_id = str(uuid.uuid4())
    now = _now_iso()
    t_start = time.monotonic()

    stats: dict = {
        "run_id": run_id,
        "dry_run": dry_run,
        "playbook": {"updated": 0, "silent_bumped": 0},
        "campaign": {"updated": 0, "silent_bumped": 0},
        "source_ip": {"updated": 0, "silent_bumped": 0},
        "errors": [],
    }

    # --- Playbooks ---------------------------------------------------------
    for pb in _iter_current_playbooks(es, cowrie_idx.session_clusters, cowrie_idx.sessions_rollup):
        snapshot = {
            "run_id":           run_id,
            "@timestamp":       now,
            "session_count":    pb["session_count"],
            "ip_count":         pb["ip_count"],
            "mean_novelty":     pb["mean_novelty"],
            "dominant_intent":  pb.get("dominant_intent"),
            "asn_top":          pb.get("asn_top"),
            "asn_distribution": pb.get("asn_distribution") or {},
        }
        if dry_run:
            stats["playbook"]["updated"] += 1
            continue
        try:
            update_playbook_lifecycle(
                es, f_idx.playbook_lifecycle,
                playbook_id=pb["playbook_id"],
                playbook_name=pb.get("playbook_name"),
                run_id=run_id,
                snapshot=snapshot,
                snapshot_cap=cap,
            )
            stats["playbook"]["updated"] += 1
        except Exception as exc:
            stats["errors"].append({"layer": "playbook", "id": pb["playbook_id"], "error": str(exc)})

    # --- Campaigns ---------------------------------------------------------
    for c in _iter_current_campaigns(es, cowrie_idx.campaigns):
        snapshot = {
            "run_id":           run_id,
            "@timestamp":       now,
            "session_count":    c["session_count"],
            "ip_count":         c["ip_count"],
            "mean_novelty":     c["mean_novelty"],
            "dominant_intent":  c.get("dominant_intent"),
            "asn_top":          c.get("asn_top"),
            "asn_distribution": c.get("asn_distribution") or {},
        }
        if dry_run:
            stats["campaign"]["updated"] += 1
            continue
        try:
            update_campaign_lifecycle(
                es, f_idx.campaign_lifecycle,
                campaign_id=c["campaign_id"],
                campaign_name=c.get("campaign_name"),
                campaign_kind=c.get("campaign_kind"),
                run_id=run_id,
                snapshot=snapshot,
                snapshot_cap=cap,
            )
            stats["campaign"]["updated"] += 1
        except Exception as exc:
            stats["errors"].append({"layer": "campaign", "id": c["campaign_id"], "error": str(exc)})

    # --- Source IPs --------------------------------------------------------
    for ip in _iter_current_ips(es, cowrie_idx.ips_rollup):
        snapshot = {
            "run_id":                  run_id,
            "@timestamp":              now,
            "session_count":           ip["session_count"],
            "dominant_playbook_id":    ip.get("dominant_playbook_id"),
            "playbook_distribution":   ip.get("playbook_distribution") or {},
            "intel_verdict":           ip.get("intel_verdict"),
            "intel_consensus_score":   ip.get("intel_consensus_score"),
            "asn":                     ip.get("asn"),
            "geo_country":             ip.get("geo_country"),
        }
        if dry_run:
            stats["source_ip"]["updated"] += 1
            continue
        try:
            update_source_ip_lifecycle(
                es, f_idx.source_ip_lifecycle,
                source_ip=ip["source_ip"],
                run_id=run_id,
                snapshot=snapshot,
                snapshot_cap=cap,
            )
            stats["source_ip"]["updated"] += 1
        except Exception as exc:
            stats["errors"].append({"layer": "source_ip", "id": ip["source_ip"], "error": str(exc)})

    # --- Silent-run bump on the artifacts we did NOT touch this run --------
    if not dry_run:
        # Refresh the lifecycle indexes once so the just-written docs are
        # visible to the update_by_query below.
        try:
            es.indices.refresh(index=",".join([
                f_idx.playbook_lifecycle,
                f_idx.campaign_lifecycle,
                f_idx.source_ip_lifecycle,
            ]))
        except Exception:
            pass
        stats["playbook"]["silent_bumped"]  = increment_silent_runs(es, f_idx.playbook_lifecycle,  current_run_id=run_id)
        stats["campaign"]["silent_bumped"] = increment_silent_runs(es, f_idx.campaign_lifecycle, current_run_id=run_id)
        stats["source_ip"]["silent_bumped"] = increment_silent_runs(es, f_idx.source_ip_lifecycle, current_run_id=run_id)

    stats["runtime_seconds"] = round(time.monotonic() - t_start, 2)
    return stats
